// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhlv3eyTjiwp6FZ3EXP-3BpYldGlpdQJs',
    appId: '1:1084624060866:web:9215e5205d93a43e50565b',
    messagingSenderId: '1084624060866',
    projectId: 'hankamel-talem',
    authDomain: 'hankamel-talem.firebaseapp.com',
    storageBucket: 'hankamel-talem.firebasestorage.app',
    measurementId: 'G-KYGHMC93GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZKRhwUS-MpxO4L9Ao7Lv9tR_BJENZ2E',
    appId: '1:1084624060866:android:46453d926d85784a50565b',
    messagingSenderId: '1084624060866',
    projectId: 'hankamel-talem',
    storageBucket: 'hankamel-talem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZTLFVjzNxsRHt4U-wUY_olx2j4AA_i3Y',
    appId: '1:1084624060866:ios:a2937d062f36327150565b',
    messagingSenderId: '1084624060866',
    projectId: 'hankamel-talem',
    storageBucket: 'hankamel-talem.firebasestorage.app',
    iosBundleId: 'hs.hankammelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZTLFVjzNxsRHt4U-wUY_olx2j4AA_i3Y',
    appId: '1:1084624060866:ios:a2937d062f36327150565b',
    messagingSenderId: '1084624060866',
    projectId: 'hankamel-talem',
    storageBucket: 'hankamel-talem.firebasestorage.app',
    iosBundleId: 'hs.hankammelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhlv3eyTjiwp6FZ3EXP-3BpYldGlpdQJs',
    appId: '1:1084624060866:web:59964a4a9ceb6dd450565b',
    messagingSenderId: '1084624060866',
    projectId: 'hankamel-talem',
    authDomain: 'hankamel-talem.firebaseapp.com',
    storageBucket: 'hankamel-talem.firebasestorage.app',
    measurementId: 'G-K521KCC6QL',
  );
}
